### ISSUE TITLE
domains view generation 

### ISSUE THREAD

**Issue by kmacpher67** [willcrisis/bootstrap-layouts#2]
I generated a Controller View for a domain but the layout was not "bootstrapized" 

Was the generation template integration supposed to work? 

Do I need to install the "templates" engine to get this to work properly? 
`grails install-templates`

Again Thanks, great job.

**Comment by willcrisis** [comment]
Hello, @kmacpher67.

Thanks for your interest in this project!

Unfortunately, the view generation does not work. I've found some issues working with [grails-fields plugin](https://github.com/grails-fields-plugin/grails-fields), that is the new way of generating views. Because of these issues, I decided to let view generation out of the scope.
If you find a way to make it work, feel free to make a PR!
